(define (problem blockProblem)
  (:domain blockWorld)
  (:objects A B C D - block)
  (:init (ontable D)
         (ontable A)
         (on C D)
         (on B A)
         (clear B)
         (clear C)
         (handempty))
  (:goal (and (on A B) 
         (on B C) 
         (on C D) 
         (ontable D) 
         (clear A) 
         (handempty))))