(define (problem blockProblem)
  (:domain blockWorld)
  (:objects A B C D E F G H I J - block)
  (:init (ontable A)
         (on B A)
         (on C B)
         (clear C)
         (ontable D)
         (on E D)
         (on F E)
         (clear F)
         (ontable G)
         (clear G)
         (ontable I)
         (on J H)
         (on H I)
         (clear J)
         (handempty))
  (:goal (and (ontable J)
         (on A B) 
         (on B C) 
         (on C D)
         (on D E)
         (on E F)
         (on F G)
         (on G H)
         (on H I)
         (on I J)
         (clear A) 
         (handempty))))