(define (problem planeProblem)
  (:domain planeWorld)
  (:objects C1 C2 C3 - cargo A1 A2 - plane TEG CDG BAR -airport)
  (:init (situeC C1 TEG) 
         (situeC C2 TEG)
         (situeC C3 TEG)
         (situeP A1 TEG)
         (situeP A2 TEG)
         (vide A1)
         (vide A2)
  )
  (:goal (and (situeC C1 BAR) 
         (situeC C2 BAR)
         (situeC C3 BAR)
         (situeP A1 CDG)
         (situeP A2 CDG)))
  )